import pandas as pd

# Load the master matrix generated by your ingestion script
df = pd.read_csv('data/processed/master_health_matrix.csv')

# Calculate the Residual Gap: The delta between institutional treatment 
# capacity and the baseline prevalence established in academic studies.
df['estimated_untreated'] = (df['prevalence_study_index'] * 1000000) - df['treated_count']

# Export the final analytical findings
df.to_csv('data/processed/analytical_gap_results.csv', index=False)
